Repository scikit-hep/pylhe, pull requests merged in 2020-07, with the labels that each got.

#35 ci: Separate linting from testing
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/publish-package.yml
  setup.py
Labels: CI

#29 test: Add unit tests to CI
  .coveragerc
  .github/workflows/ci.yml
  codecov.yml
  pyproject.toml
  pytest.ini
  setup.py
  tests/test_lhe_reader.py
Labels: CI, test

#36 chore: Add Codecov coverage badge
  README.md
Labels: chore

#37 docs: Add preferred BibTeX citation to README
  .bumpversion.cfg
  .zenodo.json
  README.md
Labels: docs
