Repository scikit-hep/pylhe, pull requests merged in 2020-10, with the labels that each got.

#27 feat: Use particle for labeling in visualizations
  setup.cfg
  src/pylhe/__init__.py
Labels: enhancement

#44 ci: Publish releases to PyPI through GitHub releases
  .github/workflows/publish-package.yml
Labels: CI

#45 fix: Don't run publishing workflow on tags to avoid errors
  .github/workflows/publish-package.yml
Labels: CI, fix
