Repository scikit-hep/pylhe, pull requests merged in 2022-10, with the labels that each got.

#148 docs: Add project logo
  README.md
  docs/_static/img/pylhe-logo.png
Labels: docs

#150 docs: Add Conda badge to README
  README.md
Labels: docs, chore

#153 ci: Enable Dependabot version updates for GitHub Actions
  .github/dependabot.yml
Labels: CI, chore

#156 build: Support Python 3.7+
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  setup.cfg
Labels: CI, build
