Repository scikit-hep/pylhe, pull requests merged in 2022-05, with the labels that each got.

#123 ci: Add semantic PR check GHA workflow
  .github/workflows/semantic-pr-check.yml
Labels: CI

#118 feat: Add IPython visualisation and switch to graphviz
  setup.cfg
  src/pylhe/__init__.py
  tests/test_visualize.py
Labels: enhancement, test, API

#124 refactor: Use absolute imports over explicit relative imports
  .pre-commit-config.yaml
  src/pylhe/__init__.py
Labels: chore, refactor

#125 feat: Use tbump over bump2version
  .bumpversion.cfg
  setup.py
  tbump.toml
Labels: enhancement
