Repository scikit-hep/pylhe, pull requests merged in 2022-08, with the labels that each got.

#131 build: Decouple and minimise dependencies for visualisation
  README.md
  setup.cfg
  setup.py
  src/pylhe/__init__.py
  tests/test_api.py
  tests/test_visualize.py
Labels: enhancement, build

#136 ci: Add tests for LHEEventInfo, LHEParticle, LHEFile classes
  src/pylhe/__init__.py
  tests/test_api.py
  tests/test_classes.py
Labels: enhancement, CI, API

#137 chore: Add black profile to isort
  pyproject.toml
Labels: CI, chore

#138 ci: Add bump version workflow for release tags
  .github/workflows/bump-version.yml
Labels: CI

#139 feat: Read LHE file version
  src/pylhe/__init__.py
  tests/test_lhe_reader.py
Labels: enhancement
