Repository scikit-hep/pylhe, pull requests merged in 2023-01, with the labels that each got.

#174 docs: update examples/awkward_example.ipynb
  examples/awkward_example.ipynb
Labels: docs

#175 chore: Update references to default branch to 'main'
  .github/workflows/bump-version.yml
  .github/workflows/ci.yml
  .github/workflows/publish-package.yml
  README.md
Labels: chore

#176 ci: Publish to TestPyPI on tag or by workflow dispatch trigger
  .github/workflows/publish-package.yml
Labels: CI

#178 fix: Correct YAML
  .github/workflows/publish-package.yml
Labels: fix

#180 fix: Update KeyError to new exception of DirectionalMap
  src/pylhe/__init__.py
  tests/test_visualize.py
Labels: fix
