Repository scikit-hep/pylhe, pull requests merged in 2024-10, with the labels that each got.

#262 chore: add 3.13 classifier and test
  .github/workflows/ci.yml
  pyproject.toml
Labels: chore

#265 ci: use latest available python for lint and publish
  .github/workflows/lint.yml
  .github/workflows/publish-package.yml
Labels: CI

#256 docs: LHE file writing examples
  README.md
  examples/filter_events_example.ipynb
  examples/write_monte_carlo_example.ipynb
  src/pylhe/__init__.py
  tests/test_api.py
  tests/test_lhe_reader.py
Labels: docs
